services:
    api:
        build:
            context: .
            target: development
            dockerfile: apps/api/Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./apps/api
                  target: /app/apps/api
                  ignore:
                      - node_modules/
                      - drizzle/
                  initial_sync: true
                - action: sync+restart
                  path: ./packages
                  target: /app/packages
                  ignore:
                      - node_modules/
                  initial_sync: true
                - action: rebuild
                  path: apps/api/package.json
                - action: rebuild
                  path: packages/*/package.json
        environment:
            - NODE_ENV=development
            - DB_FILE_PATH=/app/data/db.sqlite
            - JWT_SECRET=${JWT_SECRET-please_change_me}
            - MANDATS_PATH=${MANDATS_PATH-./data/mandats}
            - MS_ACCESS_DB_PATH=${MS_ACCESS_DB_PATH-./data/BEGdatas.mdb}
        volumes:
            - ./apps/api/drizzle:/app/apps/api/drizzle
            - ./data:/app/data
            - ./export-mdb:/app/export-mdb
            - ./initial-data:/app/initial-data
            - $MANDATS_PATH:/mandats
            - $MS_ACCESS_DB_PATH:/export-mdb/beg.mdb:ro
            - $FILE_STORAGE:/app/files
        working_dir: /app/apps/api
        command: bun run dev
        ports:
            - 4983:3000
    app:
        build:
            context: .
            target: development
            dockerfile: apps/app/Dockerfile
        develop:
            watch:
                - action: sync
                  path: ./apps/app
                  target: /app/apps/app
                  ignore:
                      - node_modules/
                  initial_sync: true
                - action: sync+restart
                  path: ./packages
                  target: /app/packages
                  ignore:
                      - node_modules/
                  initial_sync: true
                - action: rebuild
                  path: ./apps/app/package.json
                - action: rebuild
                  path: ./packages/*/package.json
        environment:
            - NODE_ENV=development
            - VITE_HMR_HOST=0.0.0.0
            - VITE_HMR_PORT=8080
        working_dir: /app/apps/app
        command: bun run dev

    proxy:
        restart: "on-failure"
        container_name: "proxy"
        build:
            context: ./provision/nginx
            dockerfile: Dockerfile
            target: development
        ports:
            - 8084:80
        develop:
            watch:
                - action: sync+restart
                  path: ./provision/nginx/nginx.dev.conf
                  target: /etc/nginx/nginx.conf
